Traceback (most recent call last):
  File "/home/users/sabayev/MaiganeEM/stageEM/./sendOut.py", line 95, in <module>
    postProcess(paramFilePath)
  File "/home/users/sabayev/MaiganeEM/stageEM/./sendOut.py", line 78, in postProcess
    run_end(paramFilePath,df,y,taskType)
  File "/home/users/sabayev/.local/lib/python3.12/site-packages/stabl/sherlock.py", line 121, in run_end
    prd = prd[data.index]
          ~~~^^^^^^^^^^^^
  File "/home/users/sabayev/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/sabayev/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/users/sabayev/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6249, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['slide1_P01endoIMC_mgd_UC755_1_4', 'slide1_P01endoIMC_mgd_UC755_2_5',\n       'slide1_P01endoIMC_mgd_UC755_3_6', 'slide10_P01endoIMC_mgd_UC724_1_4',\n       'slide10_P01endoIMC_mgd_UC724_2_5', 'slide10_P01endoIMC_mgd_UC724_3_6',\n       'slide11_P01endoIMC_mgd_CNC12_2_5', 'slide11_P01endoIMC_mgd_CNC12_3_6',\n       'slide11_P01endoIMC_mgd_CNC12_4_7', 'slide12_P01endoIMC_mgd_UC733_1_4',\n       ...\n       'slide5_P01endoIMC_mgd_UC231_3_6', 'slide6_P01endoIMC_mgd_CNC07_1_4',\n       'slide6_P01endoIMC_mgd_CNC07_2_5', 'slide6_P01endoIMC_mgd_CNC07_3_6',\n       'slide8_P01endoIMC_mgd_CNC29_1_4', 'slide8_P01endoIMC_mgd_CNC29_2_5',\n       'slide8_P01endoIMC_mgd_CNC29_3_6', 'slide9_P01endoIMC_mgd_UC657_1_4',\n       'slide9_P01endoIMC_mgd_UC657_2_5', 'slide9_P01endoIMC_mgd_UC657_3_6'],\n      dtype='object', length=109)] are in the [columns]"

real	0m28.860s
user	0m10.679s
sys	0m2.560s
